package ${package} {

	import org.adaptiveplatform.communication.Enum;
	
	/**
	 * NOTE: This file is autogenerated and will be overwritten every time.
	 */	
	[RemoteClass(alias="${originalPackage}.${originalName}")]
	public class ${name} extends Enum {

		<#list constants as constant>
		public static const ${constant}:${name} = new ${name}("${constant}");
		</#list> 

		public function ${name}(name:String = null) {
			super(name);
		}
	}
}
