package ${package} {
	
	<#list imports as import>
  	import ${import.package}.${import.name};
	</#list>
	import org.adaptiveplatform.communication.ResultHandler;

	/**
	 * NOTE: This file is autogenerated and will be overwritten every time.
	 */
	public interface ${name} {
	
		<#list methods as method>
		/**
			<#if method.hasGenericParameter>
			</#if>
		 * @returns ${method.returnType.name} <#if method.returnType.generic>of <#list method.returnType.actualGenericArguments as generic>${generic.name}<#if generic_has_next>, </#if></#list></#if>
		 */
		function ${method.name}(<#list method.parameters as parameter>${parameter.name}:${parameter.type.name}<#if parameter_has_next>, </#if></#list>):ResultHandler;
		
		</#list>
	}
}
