package ${package} {
	
	<#list imports as import>
  	import ${import.package}.${import.name};
	</#list>
	
	import org.adaptiveplatform.communication.RemoteService;
	import org.adaptiveplatform.communication.ResultHandler;
	
	import mx.messaging.ChannelSet;
	import mx.rpc.remoting.RemoteObject;

	/**
	 * NOTE: This file is autogenerated and will be overwritten every time.
	 */
	public class Remote${name} implements ${name}{
			
		public var remoteService:RemoteService;
		
		public function Remote${name}() {
		}
		
		<#list methods as method>
		public function ${method.name}(<#list method.parameters as parameter>${parameter.name}:${parameter.type.name}<#if parameter_has_next>, </#if></#list>):ResultHandler{
			return remoteService.call("${beanName}", "${method.name}"<#if (method.parameters?size > 0)>, <#list method.parameters as parameter>${parameter.name}<#if parameter_has_next>, </#if></#list></#if>);
		}
		
		</#list>
	}
}
