package ${package} {

	/**
	 * NOTE: This file is autogenerated, but will ONLY be created if it doesn't already exist.
	 */	
	[Bindable]
	[RemoteClass(alias="${originalPackage}.${originalName}")]
    public class ${name} extends ${name}Base{
    
    	public function ${name}(){
		}
	}
}
