package org.adaptiveplatform.codegenerator.acceptance {
	
  	import mx.collections.ArrayCollection;
  	import mx.collections.ArrayCollection;
	
	import org.adaptiveplatform.communication.RemoteService;
	import org.adaptiveplatform.communication.ResultHandler;
	
	import mx.messaging.ChannelSet;
	import mx.rpc.remoting.RemoteObject;

	/**
	 * NOTE: This file is autogenerated and will be overwritten every time.
	 */
	public class RemoteSampleDao implements SampleDao{
			
		public var remoteService:RemoteService;
		
		public function RemoteSampleDao() {
		}
		
		public function getUser(number:Number):ResultHandler{
			return remoteService.call("sampleDao", "getUser", number);
		}
		
		public function count(arrayCollection:ArrayCollection):ResultHandler{
			return remoteService.call("sampleDao", "count", arrayCollection);
		}
		
		public function query(string:String):ResultHandler{
			return remoteService.call("sampleDao", "query", string);
		}
		
	}
}
