package org.adaptiveplatform.codegenerator.acceptance {
	

	/**
	 * NOTE: This file is autogenerated and will be overwritten every time.
	 */	
	[Bindable]
	public class SampleCommandBase {

		[SampleConstraint(min=5, max=2147483647)]
  		public var name:String;
  		
  		public var description:String;
  		
		public function SampleCommandBase(){
		}
	}
}
