package org.adaptiveplatform.codegenerator.acceptance {
	
  	import mx.collections.ArrayCollection;

	/**
	 * NOTE: This file is autogenerated and will be overwritten every time.
	 */	
	[Bindable]
	public class SampleDtoBase {

  		public var id:Number;
  		
  		public var name:String;
  		
  		public var email:String;
  		
		/**
		 * ArrayCollection of String
		 */
  		public var roles:ArrayCollection;
  		
		public function SampleDtoBase(){
		}
	}
}
