package org.adaptiveplatform.codegenerator.acceptance {

	/**
	 * NOTE: This file is autogenerated, but will ONLY be created if it doesn't already exist.
	 */	
	[Bindable]
	[RemoteClass(alias="org.adaptiveplatform.codegenerator.acceptance.SampleDto")]
    public class SampleDto extends SampleDtoBase{
    
    	public function SampleDto(){
		}
	}
}
